### ISSUE TITLE
guest network doesn't pass traffic between nodes

### ISSUE THREAD

**Issue by davidvossel** [kubernetes-sigs/cluster-api-provider-kubevirt#179]
Using calico on the infra cluster and calico on the guest cluster causes issues. Network traffic on the guest cluster cannot communicate between nodes.

**Comment by davidvossel** [comment]
this should be solved by offsetting the vxlan port on calico in the guest cluster. The vxlan ports can not overlap between the guest and infra cluster.

Also the cidr ranges between infra and guest cluster must be offset.

**Comment by salilhpe** [comment]
here  are changes that I did  the trick for me. (Added a new variable FELIX_VXLANPORT that  specified the new port and enabled vxlan instead of IPIP)
--- calico.yaml	2022-09-06 19:55:16.904966022 +0000
***************
*** 4509,4524 ****
                    key: calico_backend
              # Cluster type to identify the deployment type
              - name: CLUSTER_TYPE
!               value: "k8s,bgp"
              # Auto-detect the BGP IP address.
              - name: IP
                value: "autodetect"
              # Enable IPIP
              - name: CALICO_IPV4POOL_IPIP
!               value: "Always"
              # Enable or Disable VXLAN on the default IP pool.
              - name: CALICO_IPV4POOL_VXLAN
!               value: "Never"
              # Enable or Disable VXLAN on the default IPv6 IP pool.
              - name: CALICO_IPV6POOL_VXLAN
                value: "Never"
--- 4509,4524 ----
                    key: calico_backend
              # Cluster type to identify the deployment type
              - name: CLUSTER_TYPE
!               value: "k8s"
              # Auto-detect the BGP IP address.
              - name: IP
                value: "autodetect"
              # Enable IPIP
              - name: CALICO_IPV4POOL_IPIP
!               value: "Never"
              # Enable or Disable VXLAN on the default IP pool.
              - name: CALICO_IPV4POOL_VXLAN
!               value: "Always"
              # Enable or Disable VXLAN on the default IPv6 IP pool.
              - name: CALICO_IPV6POOL_VXLAN
                value: "Never"
***************
*** 4560,4565 ****
--- 4560,4567 ----
                value: "false"
              - name: FELIX_HEALTHENABLED
                value: "true"
+             - name: FELIX_VXLANPORT
+               value: "6789"
            securityContext:
              privileged: true
            resources:

P.S. I selected the  port number randomly, not sure if 6789 is reserved for any service.
