### ISSUE TITLE
ssh validation code is specific for cloud init

### ISSUE THREAD

**Issue by nirarg** [kubernetes-sigs/cluster-api-provider-kubevirt#26]
Hi,

As part of KubevirtMachine Reconcile, there is ssh validation for:
1. VM is booted
2. Bootstrap is completed

This validation assumes the following:
1. The VM support cloudinit format (for example fedora)
2. When the bootstrap is done the file `/run/cluster-api/bootstrap-success.complete` is created on the VM file system

Those assumptions are not true for Openshift cluster scenario:
1. The Nodes run RHCOS 
2. RHCOS use ignitons and not cloud init
3. Users and ssh keys are added in different format in RHCOS
4.  The `/run/cluster-api/bootstrap-success.complete` file isn't created when the bootstrap is done

I can think of two possible solutions:
1. Change the validation to use more generic way, not ssh (does Kubevirt provide something like this?)
2. Add another parameter to KubevirtMachine indicates which OS used, have different validation for each OS

**Comment by davidvossel** [comment]
The appending of the user+ssh key to the bootstrap's userdata is problematic. The logic today is assuming that the cloud-init user-data is structured as the `cloud-config` type. There are no guarantees that is the case. There are many cloud-init formats [1]

If we really need this ssh behavior as it is today, my suggestion is to make it only apply when the user-data is of type `cloud-config` which I believe can be detected accurately by looking for the `#cloud-config` string at the beginning of the user-data.

We could make the following changes to be backwards compatible with the existing behavior and work with the openshift use case.

* when SSH+capk keys are injected (because cloud-config user-data is used), then continue the current mode of operation
* when userdata is not of type `cloud-config`, use the VMI's readiness condition to determine when it has booted.
* Make the the `kubevirtMachine.Spec.Bootstrapped` boolean an optional pointer, that is only set to non-nil value when we can actually detect that bootstrapping occurred (requires ssh access). Without ssh access, the bootstrapped boolean will never get set and be ignored.

would that be reasonable?

1. https://cloudinit.readthedocs.io/en/latest/topics/format.html#mime-multi-part-archive

**Comment by agradouski** [comment]
@davidvossel @nirarg -- agree we can check for `#cloud-config` to validate that user data is really of type cloud-config.
we realized that using ssh to validate that VM has booted/bootstrapped was not ideal, and implemented ssh-based validation for time being until we could figure out a more generic solution.

thanks for logging this issue.
